ignores:
  # monorepo deps
  - 'ava'
  - '@types/npmcli__promise-spawn'

  # only types (from @types/npmcli__promise-spawn) are referenced
  - '@npmcli/promise-spawn'
  - '@types/micromatch'
  - '@yarnpkg/core'
  - '@yarnpkg/shell'
