FROM docker.io/library/node:18-alpine@sha256:3482a20c97e401b56ac50ba8920cc7b5b2022bfc6aa7d4e4c231755770cf892f
RUN apk add --no-cache git
WORKDIR /app
COPY . .
RUN npm i -g verdaccio && chown -R node:node /app
USER node
RUN git config --global user.email "you@example.com" && \
  git config --global user.name "Your Name" && \
  mkdir -p /app/verdaccio/storage && \
  npm install && \
  npm run setup && \
  npm run build
ENTRYPOINT ["/usr/local/bin/npm"]
