FROM node:18-alpine
RUN apk add --no-cache git
WORKDIR /app
COPY . .
RUN npm i -g verdaccio && chown -R node:node /app
USER node
RUN git config --global user.email "you@example.com" && \
  git config --global user.name "Your Name" && \
  mkdir -p /app/verdaccio/storage && \
  npm install && \
  npm run setup && \
  npm run build
ENTRYPOINT ["/usr/local/bin/npm"]
